### DISCUSSION TITLE
Please some help to setup S3 as file storage

### DISCUSSION THREAD

**Discussion by ivancarlosti** [pglombardo/PasswordPusher#2072] [Q&A]
Hi team,

Please, someone have a clue of how can I troubleshoot my S3 bucket to make it works?

This is my settings:

```
  storage: 'amazon'
  s3:
    endpoint: 'https://mybucket.s3-website.sa-east-1.amazonaws.com'
    access_key_id: 'mykey'
    secret_access_key: 'mysecret'
    region: 'sa-east-1'
    bucket: 'mybucket'
```

This is my bucket CORS:

```
[
    {
        "AllowedHeaders": [
            "Content-Type",
            "Content-MD5",
            "Content-Disposition"
        ],
        "AllowedMethods": [
            "PUT"
        ],
        "AllowedOrigins": [
            "https://mydomain"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3600
    }
]
```

And this is my key IAM policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::mybucket/*"
        }
    ]
}
```

Please, am I missing something?
