### DISCUSSION TITLE
How to configure worker to delete expired files?

### DISCUSSION THREAD

**Discussion by ivancarlosti** [pglombardo/PasswordPusher#2769] [Q&A] [answered]
I added pwpusher-worker on my docker and looks that's OK, I can now see "Background Jobs" on my admin dashboard, but I do not know how to make it works to expires and delete expired files pushed. What am I missing? There is any documentation regarding this?

![image](https://github.com/user-attachments/assets/12b96dea-6b4e-48b9-a2cd-2eec38f0d198)

Thanks a lot and regards

**Comment by pglombardo** [comment]
Hi @ivancarlosti - the background jobs are automatic and are scheduled to run every 4 hours I believe.

When running `pwpush-worker`,  make sure it has identical access to where your files are stored (e.g. S3 or a shared local filesystem).  Without this, it won't be able to delete files attached to pushes.

You can also manually trigger job runs with v1.48.2.  I put together docs on this last night:
https://docs.pwpush.com/docs/background-tasks/#running-the-background-tasks

**Comment by ivancarlosti** [comment]
My Recurring tasks is empty, maybe I missed something :/

![image](https://github.com/user-attachments/assets/1414b8bc-5a8d-46b8-9f13-fa4d8e5eb15d)

My compose:

```
name: <dockername>

x-op-app-environment: &x-op-app-environment
  environment:
    DATABASE_URL: 'mysql2://<user>:<pass>@host.docker.internal:3306/<db>'

services:
  pwpush:
    image: docker.io/pglombardo/pwpush:latest
    container_name: <containername>
    volumes:
      - type: bind
        source: ./settings.yml
        target: /opt/PasswordPusher/config/settings.yml
    ports:
      - "5100:5100"
    <<: *x-op-app-environment
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  worker:
    container_name: <containername2>
    image: docker.io/pglombardo/pwpush-worker:latest
    restart: unless-stopped
    <<: *x-op-app-environment
    depends_on:
      - pwpush
```

**Reply by pglombardo** [reply]
When was the last time you re-fetched the Docker image?  `docker pull pglombardo/pwpush-worker:latest`

**Reply by pglombardo** [reply, marked as answer]
BTW you should also mount the `settings.yml` in the worker container: `target: /opt/PasswordPusher/config/settings.yml`

**Comment by ivancarlosti** [comment]
You got it!!! Thank you!!!

That's my new docker compose, I also forgot to add `host.docker.internal` for worker, so it was not finding my DB host 🤦‍♂️ so I added volumes and extra_hosts on x-op-app-environment to share everything with worker ;)

```
name: ############

x-op-app-environment: &x-op-app-environment
  environment:
    DATABASE_URL: 'mysql2://############:############@host.docker.internal:3306/############'
    GA_ENABLE: "true"
    GA_ACCOUNT: "############"
    GA_DOMAIN: "############"
  volumes:
    - type: bind
      source: ./settings.yml
      target: /opt/PasswordPusher/config/settings.yml
  extra_hosts:
    - host.docker.internal:host-gateway

services:
  pwpush:
    container_name: ############
    image: docker.io/pglombardo/pwpush:latest
    ports:
      - "5100:5100"
    <<: *x-op-app-environment
    restart: unless-stopped

  worker:
    container_name: ############
    image: docker.io/pglombardo/pwpush-worker:latest
    <<: *x-op-app-environment
    depends_on:
      - pwpush
    restart: unless-stopped
```

Thanks a lot!!
