### ISSUE TITLE
Kubernetes Pod replies "403 Forbiden" after a while

### ISSUE THREAD

**Issue by dhardy92** [pglombardo/PasswordPusher#1106]
## 🐛 Bug Report
I was trying to deploy pwpsuh on Google GKE but after a while when using httpGet readinessProbe and livenessProbe on port 5100 path /, pod turn unealthy and reboot  container (livenessProbe do its job)
Event show that probes get 403 answer form pwpush service.

## 🔬 How To Reproduce

1. run a GKE deployement
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwpush
  name: pwpush
  namespace: infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pwpush
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pwpush
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: PWP__EXPIRE_AFTER_DAYS_DEFAULT
          value: "1"
        - name: PWP__EXPIRE_AFTER_VIEWS_DEFAULT
          value: "2"
        - name: PWP__LOG_LEVEL
          value: info
        image: pglombardo/pwpush-ephemeral:1.28.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5100
          timeoutSeconds: 1
        name: pwpush
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5100
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
          requests:
            cpu: 20m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
```

2. Wait some time (~30min) and readinessProbe shows warns
![image](https://github.com/pglombardo/PasswordPusher/assets/898473/7452264f-db1c-406f-a849-81cc7896adfe)

3. open a shell on running Pod and simulate probe for a while:
`kubectl exec -ti -n infra pwpush-8447f44c78-ddrmh  -- /bin/bash`
```
pwpush-8447f44c78-ddrmh:/opt/PasswordPusher$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if1392: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1460 qdisc noqueue state UP 
    link/ether 4e:2f:e0:41:1e:ed brd ff:ff:ff:ff:ff:ff
    inet 10.91.8.22/32 scope global eth0
       valid_lft forever preferred_lft forever
pwpush-8447f44c78-ddrmh:/opt/PasswordPusher$ while true ; do wget -O /dev/null -o - -S http://10.91.8.22:5100/ 2>&1 | grep 'HTTP/1.1' ; sleep 10 ; done
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 200 OK
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 200 OK
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
```

( 194 "200 OK" before first fails = 10s sleep * 194 = 1940 seconds = 32 min )

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker
  - [x] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [x] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher? 1.28.6

## 📈 Expected behavior

Keep replying HTTP/1.1 200 for the probes on / path
