### ISSUE TITLE
Docker also for arm (rpi)

### ISSUE THREAD

**Issue by iLLiac4** [pglombardo/PasswordPusher#170]
Hi.

Is it possible to add docker for arm installation?

TNX

**Comment by pglombardo** [comment]
Docker release process would need to up be updated to use buildx: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by fiskhest** [comment]
Would you be open to change the current release process? I could try my hand at a PR.

**Comment by pglombardo** [comment]
Hi @fiskhest - this doesn't look too hard/too much work now in 2021 with Github actions.  I'm giving a shot and will post back.

**Comment by fiskhest** [comment]
Much appreciated 🙏, let me know if I can be of any assistance.

**Comment by pglombardo** [comment]
Could you try and test out this image?  All seems good but I don't have a quick way to test:
https://hub.docker.com/layers/pglombardo/pwpush-ephemeral/latest/images/sha256-869081f6c2fc496b2aa3b6ac167c29166b45645ca870d69d467ab5fc36050356?context=explore

If there aren't any issues, I'll have both pwpush-ephemeral and pwpush-postgres built automatically with arm64 going forward.

**Comment by fiskhest** [comment]
From my very limited testing it performs exactly like the official hosted alternative 💯 

Is there any interest in also including an official kubernetes manifest for the readme/installation?

**Comment by pglombardo** [comment]
> Is there any interest in also including an official kubernetes manifest for the readme/installation?

If you have one, I'd be happy to add it.  Or if you want to update the documentation yourself in a PR, by all means.  Much appreciated.

**Comment by fiskhest** [comment]
I'll post a manifest in this thread later today. Thanks 😊

**Comment by pglombardo** [comment]
#214 has been merged.  We now build both amd64 and arm64 triggered by commits on master or new semver tags being pushed.  Closing this issue now.

**Comment by fiskhest** [comment]
for @pglombardo  or whom it concerns;

this will create a deployment `pwpush`, a service `pwpush-http` and expose it for external routing using an  ingress  `pwpush-ingress`.

This requires a nginx ingress-controller deployed in the cluster or namespace, and a cert-manager cluster-issuer named `letsencrypt-prod`. It's a common setup and simplified starting point, obviously has to be adapted if the cluster is configured differently.

If you want a clean example, you can remove the keys `metadata.labels`, `spec.selector`, `spec.template` and only publish `deploy.yaml` and leave it to the operator to configure what else they expect.
For ephemeral:
```
# file: deploy.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwpush
    component: ingress-controller
    type: nginx
  name: pwpush
  namespace: pwpush
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pwpush
      component: ingress-controller
      type: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pwpush
        component: ingress-controller
        type: nginx
    spec:
      containers:
      - image: docker.io/pglombardo/pwpush-ephemeral
        imagePullPolicy: Always
        name: pwpush
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

```
# file: ingress.yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  labels:
    app: pwpush
    component: ingress-controller
    type: nginx
  name: pwpush-ingress
  namespace: pwpush
spec:
  rules:
  - host: pwpush.domain.tld
    http:
      paths:
      - backend:
          serviceName: pwpush-http
          servicePort: 5100
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - pwpush.domain.tld
    secretName: pwpush.domain.tld
```

```
# file: service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pwpush
    component: ingress-controller
    type: nginx
  name: pwpush-http
  namespace: pwpush
spec:
  ports:
  - name: http-pwpush
    port: 5100
    protocol: TCP
    targetPort: 5100
  selector:
    app: pwpush
    component: ingress-controller
    type: nginx
  sessionAffinity: None
  type: ClusterIP
```

---

For postgres, I also include a very simple configuration for deploying a persistent volume mapping `/var/lib/postgresql/data/` inside the container to the host path `/nfs/k8s/services/pwpush/data`: 
```
# file: deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwpush
    component: ingress-controller
    type: nginx
  name: pwpush
  namespace: pwpush
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pwpush
      component: ingress-controller
      type: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pwpush
        component: ingress-controller
        type: nginx
    spec:
      containers:
      - image: docker.io/pglombardo/pwpush-postgres
        imagePullPolicy: Always
        name: pwpush
        env:
          - name: DATABASE_URL
            value: postgres://passwordpusher_user:passwordpusher_passwd@localhost:5432/passwordpusher_db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: docker.io/postgres:10
        imagePullPolicy: Always
        name: postgres
        env:
          - name: POSTGRES_USER
            value: passwordpusher_user
          - name: POSTGRES_PASSWORD
            value: passwordpusher_passwd
          - name: POSTGRES_DB
            value: passwordpusher_db
        volumeMounts:
          - name: pwpush-database-data
            mountPath: /var/lib/postgresql/data
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: pwpush-database-data
        persistentVolumeClaim:
          claimName: pwpush-data-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

```
# file: ingress.yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  labels:
    app: pwpush
    component: ingress-controller
    type: nginx
  name: pwpush-ingress
  namespace: pwpush
spec:
  rules:
  - host: pwpush.domain.tld
    http:
      paths:
      - backend:
          serviceName: pwpush-http
          servicePort: 5000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - pwpush.domain.tld
    secretName: pwpush.domain.tld
```

```
# file: service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pwpush
    component: ingress-controller
    type: nginx
  name: pwpush-http
  namespace: pwpush
spec:
  ports:
  - name: http-pwpush
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pwpush
    component: ingress-controller
    type: nginx
  sessionAffinity: None
  type: ClusterIP
```

```
# file: pv.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: pwpush-data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /nfs/k8s/services/pwpush/data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
```

```
# file: pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pwpush-data-pvc
  namespace: pwpush
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pwpush-data-pv
```
