### ISSUE TITLE
Ability to remove language with `language_codes` is broken since 1.37.5

### ISSUE THREAD

**Issue by steffenbusch** [pglombardo/PasswordPusher#1904]
## 🐛 Bug Report

Since the `release` tag on dockerhub has recently moved forward from 1.36.5 to 1.37.7, my `settings.yml` configuration does no longer limit the available languages in the user-interface. Instead of just the two configured languages "de" and "en", now all languages are shown.

## 🔬 How To Reproduce

Excerpt of my `settings.yml`, which is mounted into the container as `/opt/PasswordPusher/config/settings.yml`

```yml
### Language & Internationalization
#
# List of supported languages indexed by language code.  This is used
# to build the in application language menu.
#
# To remove the availability of languages from the application entirely,
# comment out the language code(s) from the list below.
#
# <language code>: '<language name>'
language_codes:
  de: 'Deutsch'
  en: 'English'

# Used internally for the language selector model.
# This provides a conversion of language codes to
# country codes show the correct flag icons.
# See:
# https://github.com/lipis/flag-icons
# https://flagicons.lipis.dev
country_codes:
  de: :de
  en: :gb
```

I have started the container with various versions and it was working until (including) 1.37.4. 
With **1.37.5** my configuration was no longer respected and all languages are shown.

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [x] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

### Screenshots

Starting with 1.37.5 it shows all languages despite the configuration to only show "de" and "en":

![image](https://github.com/pglombardo/PasswordPusher/assets/37350514/cca002d8-80b2-4134-8e1f-87d7d370551f)

## 📈 Expected behavior

In 1.36.5 and until including 1.37.4 it was like this:

![image](https://github.com/pglombardo/PasswordPusher/assets/37350514/7c8d3898-ca5b-4882-acc1-2f234e64422f)
