### ISSUE TITLE
Error 500 on sending emails

### ISSUE THREAD

**Issue by pietro95** [pglombardo/PasswordPusher#2165]
## 🐛 Bug Report

Trying to send an email, give Error 500

## 🔬 How To Reproduce

Register a new account or try to send the confimation instruction

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [x] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher? v1.40.12

## 📈 Expected behavior

User should receive email

## 📎 Additional context

SMTP server is a Postfix Server on local network, no auth required and no TLS, simple plain SMTP on port 25.

Configuration:
```
mail:
  # Email delivery errors will be shown in the application
  # Environment Variable Override: PWP__MAIL__RAISE_DELIVERY_ERRORS='false'
  raise_delivery_errors: true

  # Allows you to use a remote mail server. Just change it from its default "localhost" setting.
  # Environment Variable Override: PWP__MAIL__SMTP_ADDRESS='smtp.example.com'
  smtp_address: '10.0.0.150'

  # If you need to specify a HELO domain, you can do it here.
  # Environment Variable Override: PWP__MAIL__SMTP_DOMAIN='xyz.dev'
  # smtp_domain: ''

  # Port of the SMTP server
  # Environment Variable Override: PWP__MAIL__SMTP_PORT='587'
  smtp_port: 25

  # If your mail server requires authentication, you need to specify the
  # authentication type here. This is a string and one of :plain (will send
  # the password in the clear), :login (will send password Base64 encoded)
  # or :cram_md5 (combines a Challenge/Response mechanism to exchange
  # information and a cryptographic Message Digest 5 algorithm to hash
  # important information)
  #
  # Important: Comment this out if your server doesn't require authentication.
  #
  # Environment Variable Override: PWP__MAIL__SMTP_AUTHENTICATION='plain'
  # smtp_authentication: 'plain'

  # If your mail server requires authentication, set the username in this setting.
  # Environment Variable Override: PWP__MAIL__SMTP_USER_NAME='apikey'
  # smtp_user_name: 'apikey'

  # If your mail server requires authentication, set the password in this setting.
  # Environment Variable Override: PWP__MAIL__SMTP_PASSWORD='something@&#$'
  # smtp_password: ''

  # Use STARTTLS when connecting to your SMTP server and fail if unsupported.
  # Environment Variable Override: PWP__MAIL__SMTP_STARTTLS='true'
  smtp_starttls: false

  # Detects if STARTTLS is enabled in your SMTP server and starts to use it. Defaults to true.
  # Environment Variable Override: PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO='false'
  smtp_enable_starttls_auto: true
  # Number of seconds to wait while attempting to open a connection.
  # Environment Variable Override: PWP__MAIL__SMTP_OPEN_TIMEOUT='10'
  smtp_open_timeout: 10

  # Number of seconds to wait until timing-out a read(2) call.
  # Environment Variable Override: PWP__MAIL__SMTP_READ_TIMEOUT='10'
  smtp_read_timeout: 10

  # When using TLS, you can set how OpenSSL checks the certificate. This is
  # useful if you need to validate a self-signed and/or a wildcard certificate.
  # This can be one of the OpenSSL verify constants, :none or :peer
  # Environment Variable Override: PWP__MAIL__SMTP_OPENSSL_VERIFY_MODE='none'
  smtp_openssl_verify_mode: 'none'

  # Configure the e-mail address which will be shown as 'From' in emails
  # See config/initializers/devise.rb where this is used
  # Environment Variable Override: PWP__MAIL__MAILER_SENDER='"Password Pusher" <pglombardo@pwpush.com>'
  mailer_sender: '"Safe Share" <safeshare@mydomain.com>'
```

Testing from inside the container give this error, which is very strange since auth should be disabled (as per config file):
```
--> Configured FROM: address: '"Safe Share" <safeshare@mydomain.com>'
D, [2024-05-22T07:49:34.944798 #59] DEBUG -- : TestMailer#send_test_email: processed outbound mail in 0.7ms
app/mailers/test_mailer.rb:7:in `send_test_email': No SMTP username provided: smtp_user_name (StandardError)
        from (irb):2:in `<main>'
irb(main):003> TestMailer.send_test_email("myemail@mydomain.com").deliver_now
```

**Comment by pglombardo** [comment]
Thanks @pietro95 - try settings `smtp_authentication: null` in your `settings.yml` file.  I suspect the default is "plain" which might be causing this.

**Comment by pietro95** [comment]
Same error, also if I look at the production log I can see this line:

```
D, [2024-05-22T09:09:52.202430 #27] DEBUG -- : source=rack-timeout id=33f9ee78-11f3-4205-a692-f097218e81b2 timeout=15000ms state=ready
D, [2024-05-22T09:09:52.205445 #27] DEBUG -- : [33f9ee78-11f3-4205-a692-f097218e81b2]   Rendering layout layouts/application.html.erb
D, [2024-05-22T09:09:52.205798 #27] DEBUG -- : [33f9ee78-11f3-4205-a692-f097218e81b2]   Rendering passwords/new.html.erb within layouts/application
D, [2024-05-22T09:09:52.205687 #27] DEBUG -- : source=rack-timeout id=33f9ee78-11f3-4205-a692-f097218e81b2 timeout=15000ms service=3ms state=active
I, [2024-05-22T09:09:52.218520 #27]  INFO -- : [33f9ee78-11f3-4205-a692-f097218e81b2] method=GET path=/it format=html controller=PasswordsController action=new status=200 allocations=6334 duration=14.02 view=13.12 db=0.00 ip=10.0.106.1 forwarded_for=10.0.106.1
D, [2024-05-22T09:09:52.219342 #27] DEBUG -- : source=rack-timeout id=33f9ee78-11f3-4205-a692-f097218e81b2 timeout=15000ms service=17ms state=completed
D, [2024-05-22T09:09:53.728478 #27] DEBUG -- : source=rack-timeout id=9f4e0ee6-7846-46cb-9fad-999b1c93e84d timeout=15000ms state=ready
D, [2024-05-22T09:09:53.734007 #27] DEBUG -- : source=rack-timeout id=9f4e0ee6-7846-46cb-9fad-999b1c93e84d timeout=15000ms service=6ms state=active
D, [2024-05-22T09:09:53.735099 #27] DEBUG -- : [9f4e0ee6-7846-46cb-9fad-999b1c93e84d]   Rendering layout layouts/login.html.erb
D, [2024-05-22T09:09:53.735235 #27] DEBUG -- : [9f4e0ee6-7846-46cb-9fad-999b1c93e84d]   Rendering devise/registrations/new.html.erb within layouts/login
I, [2024-05-22T09:09:53.772968 #27]  INFO -- : [9f4e0ee6-7846-46cb-9fad-999b1c93e84d] method=GET path=/it/utenti/sign_up format=html controller=Users::RegistrationsController action=new status=200 allocations=8163 duration=41.23 view=39.08 db=0.00 ip=10.0.106.1 forwarded_for=10.0.106.1
D, [2024-05-22T09:09:53.773666 #27] DEBUG -- : source=rack-timeout id=9f4e0ee6-7846-46cb-9fad-999b1c93e84d timeout=15000ms service=45ms state=completed
D, [2024-05-22T09:10:02.339568 #22] DEBUG -- : source=rack-timeout id=8ddc3ba6-c313-4a5d-a899-c054884bbc80 timeout=15000ms state=ready
D, [2024-05-22T09:10:02.340537 #22] DEBUG -- : source=rack-timeout id=8ddc3ba6-c313-4a5d-a899-c054884bbc80 timeout=15000ms service=1ms state=active
D, [2024-05-22T09:10:02.733748 #22] DEBUG -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80]   TRANSACTION (0.3ms)  BEGIN
D, [2024-05-22T09:10:02.735101 #22] DEBUG -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80]   User Exists? (1.7ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "verro@siciliacque.it"], ["LIMIT", 1]]
D, [2024-05-22T09:10:02.737007 #22] DEBUG -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80]   User Count (0.4ms)  SELECT COUNT(*) FROM "users" WHERE "users"."authentication_token" = $1  [["authentication_token", "-ysYxPZUtxA6qnifDfq4"]]
D, [2024-05-22T09:10:02.740114 #22] DEBUG -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80]   User Create (0.7ms)  INSERT INTO "users" ("email", "encrypted_password", "reset_password_token", "reset_password_sent_at", "remember_created_at", "sign_in_count", "current_sign_in_at", "last_sign_in_at", "current_sign_in_ip", "last_sign_in_ip", "created_at", "updated_at", "admin", "failed_attempts", "unlock_token", "locked_at", "confirmation_token", "confirmed_at", "confirmation_sent_at", "unconfirmed_email", "authentication_token") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING "id"  [["email", "verro@siciliacque.it"], ["encrypted_password", "$2a$12$k6yanKlJzMxRgrNTr1NmNOyigwRl4QLGQe6llaQb1Xj.RuSV0VQoO"], ["reset_password_token", nil], ["reset_password_sent_at", nil], ["remember_created_at", nil], ["sign_in_count", 0], ["current_sign_in_at", nil], ["last_sign_in_at", nil], ["current_sign_in_ip", nil], ["last_sign_in_ip", nil], ["created_at", "2024-05-22 09:10:02.737243"], ["updated_at", "2024-05-22 09:10:02.737243"], ["admin", false], ["failed_attempts", 0], ["unlock_token", nil], ["locked_at", nil], ["confirmation_token", "f4mHCxpwawsEark5zCn5"], ["confirmed_at", nil], ["confirmation_sent_at", "2024-05-22 09:10:02.737456"], ["unconfirmed_email", nil], ["authentication_token", "-ysYxPZUtxA6qnifDfq4"]]
D, [2024-05-22T09:10:02.741469 #22] DEBUG -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80]   TRANSACTION (0.8ms)  COMMIT
D, [2024-05-22T09:10:02.748913 #22] DEBUG -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80]   Rendering devise/mailer/confirmation_instructions.html.erb
D, [2024-05-22T09:10:02.758693 #22] DEBUG -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80] Devise::Mailer#confirmation_instructions: processed outbound mail in 16.0ms
I, [2024-05-22T09:10:02.791245 #22]  INFO -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80] Failed delivery of mail 664db66ab9671_16598f873e@60e1360e5136.mail error_class=TypeError error_message="no implicit conversion of Symbol into Integer"
D, [2024-05-22T09:10:02.791312 #22] DEBUG -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80] Date: Wed, 22 May 2024 09:10:02 +0000
From: Safe Share <safeshare@siciliacquespa.it>
Reply-To: Safe Share <safeshare@siciliacquespa.it>
To: verro@siciliacque.it
Message-ID: <664db66ab9671_16598f873e@60e1360e5136.mail>
Subject: Istruzioni per la conferma
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable
<!DOCTYPE html>
<html lang=3D"it">
<head>
  <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8=
">
  <title>Siciliacque - Condivisione dati Sensibili</title>
  <meta content=3D"Password Pusher =C3=A8 un&#39;applicazione per inviare=
 password in modo sicuro sul web. I link alle password scadono dopo un ce=
rto numero di visualizzazioni e/o dopo un certo periodo di tempo." name=3D=
'description'>
  <meta content=3D'width=3Ddevice-width, initial-scale=3D1' name=3D'viewp=
ort'>
  <link rel=3D"stylesheet" href=3D"/assets/application-c7afae36ffba9cfcf9=
6079264495770c60665e73a67e2134c876ebf900371c16.css" data-turbo-track=3D"r=
eload" />
  <script src=3D"/assets/application-d87c2becacd3dfbaac7976628d5edee5da66=
40343ba84be52b2c00dd23eca734.js" data-turbo-track=3D"reload" defer=3D"def=
er"></script>
</head>
<body class=3D"d-flex flex-column min-vh-100">
<div class=3D"container">
<h1>Conferma il tuo nuovo account</h1>
<p>Il tuo account =C3=A8 stato creato ma devi confermare di essere il pro=
prietario di questo indirizzo email.</p>
<p>
Puoi confermare l&#39;indirizzo email del tuo account tramite
<a href=3D"https://safeshare.siciliacque.it/it/utenti/confirmation?confir=
mation_token=3Df4mHCxpwawsEark5zCn5">cliccando questo link</a>
o copiando e incollando il seguente URL nel tuo browser:
</p>
<pre class=3D"chroma">
https://safeshare.siciliacque.it/it/utenti/confirmation?confirmation_toke=
n=3Df4mHCxpwawsEark5zCn5
</pre>
<p>Se non hai creato un account, non =C3=A8 richiesta alcuna azione.</p>
<p>
--
<br>
<a href=3D"https://safeshare.siciliacque.it/it">Siciliacque - Condivision=
e dati Sensibili</a>
<br>
<span class=3D"fs-6 text-muted">Usare questo portale per trasmettere dati=
 sensibili</span>
</div>
</body>
</html>
I, [2024-05-22T09:10:02.792240 #22]  INFO -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80] method=POST path=/it/utenti format=turbo_stream controller=Users::RegistrationsController action=create status=500 allocations=37612 duration=445.10 view=0.00 db=15.61 ip=10.0.106.1 forwarded_for=10.0.106.1
E, [2024-05-22T09:10:02.793919 #22] ERROR -- : [8ddc3ba6-c313-4a5d-a899-c054884bbc80]   
[8ddc3ba6-c313-4a5d-a899-c054884bbc80] TypeError (no implicit conversion of Symbol into Integer):
[8ddc3ba6-c313-4a5d-a899-c054884bbc80]   
[8ddc3ba6-c313-4a5d-a899-c054884bbc80] app/controllers/application_controller.rb:18:in `custom_set_locale_from_url'
D, [2024-05-22T09:10:02.794385 #22] DEBUG -- : source=rack-timeout id=8ddc3ba6-c313-4a5d-a899-c054884bbc80 timeout=15000ms service=455ms state=completed```

**Comment by pietro95** [comment]
Hello,

I'm trying using on PasswordPusher the same Google Workspace account used on the postfix relay (so sending directly to Google), and this is the output of the TestMailer:

```
6095304426b5:/opt/PasswordPusher$ ./bin/pwpush console
Password Pusher Version: 1.40.12
Loading production environment (Rails 7.1.3.2)
irb(main):001> TestMailer.send_test_email("myemail@mydomain.com").deliver_now

--> Configured FROM: address: '"Safe Share" <safeshare@mydomain.com>'
--> raise_delivery_errors is set to true in the configuration.  This will raise an error if the email fails to send.
--> Attempting to send a test email to myemail@mydomain.com...
--> It seems that the Email sent successfully!  Check destination inbox for the test email.

--> If you see an error, please paste this output into a GitHub issue for help.
  --> Make sure that no sensitive data is included.
  --> https://github.com/pglombardo/PasswordPusher/issues/new/choose

D, [2024-05-23T10:12:17.095316 #23] DEBUG -- : TestMailer#send_test_email: processed outbound mail in 2.3ms
I, [2024-05-23T10:12:17.493770 #23]  INFO -- : Failed delivery of mail 664f1681177e2_1713ec78788@6095304426b5.mail error_class=TypeError error_message="no implicit conversion of Symbol into Integer"
D, [2024-05-23T10:12:17.494035 #23] DEBUG -- : Date: Thu, 23 May 2024 10:12:17 +0000
From: Safe Share <safeshare@mydomain.com>
To: myemail@mydomain.com
Message-ID: <664f1681177e2_1713ec78788@6095304426b5.mail>
Subject: Test Email from Password Pusher
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

=E2=AD=90 If you are reading this, sending email works! =E2=AD=90=

(irb):1:in `<main>': no implicit conversion of Symbol into Integer (TypeError)

      OpenSSL::SSL::SSLSocket.new socket, context

```


Config:
```
mail:
  raise_delivery_errors: true
  smtp_address: 'smtp-relay.gmail.com'
  smtp_port: 587
  smtp_authentication: 'plain'
  smtp_user_name: 'relay@mydomain.com'
  smtp_password: 'myapppassword'
  smtp_starttls: true
  smtp_enable_starttls_auto: true
  smtp_open_timeout: 10
  smtp_read_timeout: 10
  smtp_openssl_verify_mode: 'peer'
  mailer_sender: '"Safe Share" <safeshare@mydomain.com>'
```
