### ISSUE TITLE
V1.50.0 Issue

### ISSUE THREAD

**Issue by blaine07** [pglombardo/PasswordPusher#2905]
v.1.50.0 will NOT stay running on Unraid.

The last thing I see:

Password Pusher: precompiling assets for customisations...

I was able to move back to 1.49.4 fine; but something about v1.50.0 is broken; on Unraid at least.

**Comment by AnID-Aux** [comment]
same here on Ubuntu 24.04 with Docker / Docker Compose:
PasswordPusher  | Tasks: TOP => assets:precompile => css:build => css:install
PasswordPusher  | (See full trace by running task with --trace)
PasswordPusher exited with code 0

**Comment by pglombardo** [comment]
Thanks @blaine07 & @AnID-Aux for the report!  Hrm v1.50.0 has some larger CSS changes that I thought wouldn't break anything - I guess I was wrong.  I'll test & fix by tomorrow.

**Comment by havedill** [comment]
Broken for me too, docker with portainer.

The container was refusing to connect to my postgres backend. Changing the take to 1.49.4 resolved

```
version: '2.1'

services:
   postgres:
     image: docker.io/postgres:16
     volumes:
       - /var/lib/postgresql/pwpush-data:/var/lib/postgresql/data
     expose:
       - "5432"
     environment: 
       POSTGRES_USER: "pwuser"
       POSTGRES_PASSWORD: "XXXXXXXXXXXXXXXXXXXXXX"
       POSTGRES_DB: "main"
     restart: unless-stopped
   pwpush:
    image: docker.io/pglombardo/pwpush:latest
    ports:
      - "5100:5100"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    restart: unless-stopped
    environment:
       # OMITTED
```
