### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/assets/roboto-latin-400-normal.woff")

### ISSUE THREAD

**Issue by ggzengel** [pglombardo/PasswordPusher#3014]
## 🐛 Bug Report

```
[2398093e-298a-4929-b6c1-62eec12b4456] ActionController::RoutingError (No route matches [GET] "/assets/roboto-slab-latin-400-normal.woff2"):
[2398093e-298a-4929-b6c1-62eec12b4456]   
E, [2025-01-25T01:41:12.010976 #27] ERROR -- : [9e97f778-9147-499f-b19e-eeb753987549]   
[9e97f778-9147-499f-b19e-eeb753987549] ActionController::RoutingError (No route matches [GET] "/assets/roboto-latin-400-normal.woff2"):
[9e97f778-9147-499f-b19e-eeb753987549]   
E, [2025-01-25T01:41:12.046665 #20] ERROR -- : [89bba545-28f2-4e77-9db1-542445128b26]   
[89bba545-28f2-4e77-9db1-542445128b26] ActionController::RoutingError (No route matches [GET] "/assets/roboto-latin-400-normal.woff"):
[89bba545-28f2-4e77-9db1-542445128b26]   
```

I use 1.50.6 

![Image](https://github.com/user-attachments/assets/871ede64-dc1b-4c3f-8e4c-27dea9d9e5fe)

```
# docker system info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.24+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1+b1
 runc version: 1.1.5+ds1-1+deb12u1
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.1.0-28-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.792GiB
 Name: lx-pwpush.extern1.local
 ID: 3BUP:RF5X:LNPQ:JNKC:CPCA:S2PP:FWD2:TFXQ:XUWN:JEU4:SLKG:EGU5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://xxxxx:xxxxx@http.http:3128
 HTTPS Proxy: http://xxxxx:xxxxx@http.http:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

I migrated from native to docker:

```
# cat docker-compose.yml 
version: '2.1'

services:

  pwpush:
    image: docker.io/pglombardo/pwpush:latest
    ports:
      - "5100:5100"
    environment:
      DATABASE_URL: "sqlite3:db/db.sqlite3"
    volumes:
    - type: bind
      source: /opt/PasswordPusher/config/settings.local.yml
      target: /opt/PasswordPusher/config/settings.local.yml
    - type: bind
      source: /opt/PasswordPusher/storage/
      target: /opt/PasswordPusher/storage/
    - type: bind
      source: /opt/PasswordPusher/db/
      target: /opt/PasswordPusher/db/
```
