### ISSUE TITLE
Jobs option is empty, passwords are not expiring after days set

### ISSUE THREAD

**Issue by nevotechsk** [pglombardo/PasswordPusher#3098]
## 🐛 Bug Report

Hi,

im running pwpusher in Docker. I have noticed that my pushes are not expiring after 7 days. They are active for unlimited time. A have updated to the latest version with Background Jobs section in Admin. But Background Job section is empty, there are no jobs specified.

When I tried to run `bin/pwpush daily_expiration` the pushes expired as expected. I aasume that periodic tasks are not running for some reason. Can anyone help how to make jobs working?

## 🔬 How To Reproduce

1. ...

### Code sample

```
db:
    image: mysql:8.0.32
    #ports:
    #  - "3306:3306"
    environment:
      MYSQL_USER: 'passwordpusher_user'
      MYSQL_PASSWORD: <PWD>
      MYSQL_DATABASE: 'passwordpusher_db'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - /var/lib/pwpush-mysql/data:/var/lib/mysql

  pwpush:
    image: docker.io/pglombardo/pwpush:latest
    environment:
      DATABASE_URL: 'mysql2://passwordpusher_user:<PWD>@db:3306/passwordpusher_db'
    ports:
      - "5100:5100"
    depends_on:
      - db
    links:
     - db:mysql
    env_file: ".env"
    volumes:
     - /opt/passwordpusher/data:/opt/PasswordPusher/storage:rw
     - /opt/passwordpusher/logo:/opt/PasswordPusher/public/logo:rw

  pggw:
    image: pglombardo/pwpush-public-gateway:latest
    environment:
      DATABASE_URL: 'mysql2://passwordpusher_user:<PWD>@db:3306/passwordpusher_db'
    ports:
      - "5101:5100"
    depends_on:
      - db
    env_file: ".env-gw"
```

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [*] Docker Image
  - [*] pwpush
  - [ ] Custom image
- [ ] Heroku
- [ ] Digital Ocean
  - [ ] App Platform
  - [ ] Kubernetes Service
- [ ] Microsoft Azure
  - [ ] App Service
  - [ ] Container Instances (ACI)
  - [ ] Kubernetes Service (AKS)
- [ ] Google Cloud
  - [ ] App Engine
  - [ ] Cloud Run
  - [ ] Kubernetes Engine
- [ ] AWS
  - [ ] Elastic Container Service (ECS)
  - [ ] Kubernetes Service (AKS)
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

### Screenshots

![Image](https://github.com/user-attachments/assets/241809e1-5ffd-4864-9b9f-89d1a8dca643)
