### ISSUE TITLE
Themes: Sandstone Nav Tabs are too bright/unreadable in dark mode

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#3102]
## 🐛 Bug Report

Can be fixed upstream or by using the following [custom CSS](https://docs.pwpush.com/docs/rebranding/#custom-css).

```css
/* Dark mode styles */
@media (prefers-color-scheme: dark) {
  ul.nav li.nav-item a.nav-link {
    background-color: #212529;
    color: #a9b0b6;
    border: 1px solid #383b3d;
  }

  ul.nav li.nav-item a.nav-link:hover {
    background-color: #0d1115;
    color: #c6cbd2;
  }

  ul.nav li.nav-item a.nav-link.active {
    background-color: #383b3d;
    color: #6ea8fe;
    font-weight: 500;
  }
}
```

## 🔬 How To Reproduce

1. ...

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] Custom image
- [ ] Heroku
- [ ] Digital Ocean
  - [ ] App Platform
  - [ ] Kubernetes Service
- [ ] Microsoft Azure
  - [ ] App Service
  - [ ] Container Instances (ACI)
  - [ ] Kubernetes Service (AKS)
- [ ] Google Cloud
  - [ ] App Engine
  - [ ] Cloud Run
  - [ ] Kubernetes Engine
- [ ] AWS
  - [ ] Elastic Container Service (ECS)
  - [ ] Kubernetes Service (AKS)
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

**Comment by TomHeim29** [comment]
Hello ! 

im in solar theme, which id like to keep for my production instance. But when a push is displayed, we cant really see the views and days  remaining, how to correct ? 
Thanks

![Image](https://github.com/user-attachments/assets/1de03456-2faf-4500-a826-cf82da3cba32)

**Comment by pglombardo** [comment]
Hi @TomHeim29 - issues are like this because we are taking off the shelf OSS themes from Bootstrap and applying them to Password Pusher.  It works for the most part but various smaller visual issues like this seem to pop up with each theme.

To fix your issue, you can apply the following custom CSS:

```css
.text-muted {
    color: var(--bs-body-color) !important;
    /* color: #171616 !important;  <---- alternative */
}

p strong {
    color: #2a2929 !important;
}
```

![Image](https://github.com/user-attachments/assets/98a6d6a5-ba5a-4298-aab9-68d9c3ccea35)

**Comment by TomHeim29** [comment]
Okay thanks, it seems like dark mode is enabled and displaying the text like this. We can't force bright mode on the theme ? 

Thanks for css it has worked !

**Comment by pglombardo** [comment]
There is no way to force just one theme (light or dark).  It's up to the theme definition.  :-/

**Comment by TomHeim29** [comment]
Okay, no problem. We can be outside of the box by using custom CSS instead, so it should be good. I need to go further and find a good looking !

**Comment by pglombardo** [comment]
CSS fix for the `Simplex` theme:

```css
@media (prefers-color-scheme: dark) {
  a div span.fs-4 {
    color: #dcd6d6;
  }
}
```

![Image](https://github.com/user-attachments/assets/2566e4aa-de33-4220-8b38-3a25798b85cb)

![Image](https://github.com/user-attachments/assets/9cf0906a-e528-477e-922e-7446035c6b58)
