### ISSUE TITLE
Image tag :latest not loading

### ISSUE THREAD

**Issue by ivancarlosti** [pglombardo/PasswordPusher#3157]
Hi team,

I tried to do a new installation using `latest` tag but it failed as below. I am using Ubuntu 24.04 in a x86 environment (AMD EPYC 7000 series processor used by Amazon t3a instances). Rolling back to `stable` tag it works fine.

```
senha         | According to DATABASE_URL database backend is set to mysql2:...
senha         |
senha         | Password Pusher: migrating database to latest...
senha         | rake aborted!
senha         | NoMethodError: undefined method 'downcase' for nil (NoMethodError)
senha         |
senha         |   config.timeout_in = Settings.login_session_timeout.to_s.strip.split(" ").then { |n, u| n.to_i.send(u.downcase.to_sym) }
senha         |                                                                                                       ^^^^^^^^^
senha         | /opt/PasswordPusher/config/initializers/devise.rb:194:in 'block (2 levels) in <main>'
senha         | /opt/PasswordPusher/config/initializers/devise.rb:194:in 'block in <main>'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/devise-4.9.4/lib/devise.rb:314:in 'Devise.setup'
senha         | /opt/PasswordPusher/config/initializers/devise.rb:11:in '<main>'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/engine.rb:689:in 'Kernel#load'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/engine.rb:689:in 'block in Rails::Engine#load_config_initializer'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/activesupport-7.2.2.1/lib/active_support/notifications.rb:212:in 'ActiveSupport::Notifications.instrument'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/engine.rb:688:in 'Rails::Engine#load_config_initializer'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/engine.rb:642:in 'block (2 levels) in <class:Engine>'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/engine.rb:641:in 'Array#each'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/engine.rb:641:in 'block in <class:Engine>'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/initializable.rb:32:in 'BasicObject#instance_exec'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/initializable.rb:32:in 'Rails::Initializable::Initializer#run'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/initializable.rb:61:in 'block in Rails::Initializable#run_initializers'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/initializable.rb:50:in 'Array#each'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/initializable.rb:50:in 'Rails::Initializable::Collection#tsort_each_child'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/initializable.rb:60:in 'Rails::Initializable#run_initializers'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/application.rb:435:in 'Rails::Application#initialize!'
senha         | /opt/PasswordPusher/config/environment.rb:7:in '<main>'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in 'Kernel#require'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/application.rb:411:in 'Rails::Application#require_environment!'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/application.rb:559:in 'block in Rails::Application#run_tasks_blocks'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/exe/rake:27:in '<top (required)>'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:58:in 'Kernel.load'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/cli.rb:455:in 'Bundler::CLI#exec'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor.rb:527:in 'Bundler::Thor.dispatch'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/exe/bundle:28:in 'block in <top (required)>'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
senha         | /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.17/exe/bundle:20:in '<top (required)>'
senha         | /usr/local/bin/bundle:25:in 'Kernel#load'
senha         | /usr/local/bin/bundle:25:in '<main>'
senha         | Tasks: TOP => db:migrate => db:load_config => environment
senha         | (See full trace by running task with --trace)
senha         | Password Pusher Version: 1.51.10
senha         |
```

Follow my docker compose:

```
name: pass

x-op-app-environment: &x-op-app-environment
  environment:
    DATABASE_URL: 'mysql2://user:pass@host.docker.internal:3306/pass'
    GA_ENABLE: "true"
    GA_ACCOUNT: "G-mytag"
    GA_DOMAIN: "domain.com"
  volumes:
    - type: bind
      source: ./settings.yml
      target: /opt/PasswordPusher/config/settings.yml
  extra_hosts:
    - host.docker.internal:host-gateway

services:
  pwpush:
    container_name: pass
    image: docker.io/pglombardo/pwpush:latest
    ports:
      - "5100:5100"
    <<: *x-op-app-environment
    restart: unless-stopped

  worker:
    container_name: pass-worker
    image: docker.io/pglombardo/pwpush-worker:latest
    <<: *x-op-app-environment
    depends_on:
      - pwpush
    restart: unless-stopped
```
