### ISSUE TITLE
docker self-built homepage can not find the login portal

### ISSUE THREAD

**Issue by chienxx** [pglombardo/PasswordPusher#3216]
I deployed the application using the following docker configuration.
```yml
x-op-app-environment: &x-op-app-environment
  environment:

    DATABASE_URL: 'postgres://pwpush_user:pwpush_passwd@db:5432/pwpush_db'

services:
  # The Password Pusher application
  pwpush:
    image: docker.io/pglombardo/pwpush:latest
    restart: unless-stopped
    ports:
      - "5100:5100"
    <<: *x-op-app-environment
    depends_on:
      - db  # Comment out if using SQLite3 (Ephemeral)
    links:
      - db:db

  worker:
    image: docker.io/pglombardo/pwpush-worker:latest
    restart: unless-stopped
    <<: *x-op-app-environment
    depends_on:
      - pwpush
      - db
    links:
     - db:db

  db:
    image: docker.io/postgres:15
    restart: unless-stopped
    volumes:
      - ./postgresql2/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pwpush_user
      POSTGRES_PASSWORD: pwpush_passwd
      POSTGRES_DB: pwpush_db

```

But i can't find where can i login.

<img width="1866" alt="Image" src="https://github.com/user-attachments/assets/33623952-a862-4cde-8484-c9961b77de71" />
