### ISSUE TITLE
Docker image not working on OpenShift since v1.50

### ISSUE THREAD

**Issue by mgollo** [pglombardo/PasswordPusher#3260]
First of all, thank you for creating PasswordPusher. It is a really valuable tool for us.
Unfortunately, recent version are no longer working for us on our OpenShift environment, see the report below.

## 🐛 Bug Report

We have been running the official PasswordPusher Docker image on our OpenShift cluster for some months now,  but pinned our production system to version 1.41.11 in August 2024 as the stable tag had been causing an issue for us back then. Our staging system was always running the latest tag, but this stopped working when latest became 1.50. I didn't manage to analyse the situation until today, but I can report that all versions up to the latest 1.49 are working. Both the latest 1.50 and 1.51 do not work.
I am attaching the logs for both versions. As far as I can tell, this is caused by [this line](https://github.com/pglombardo/PasswordPusher/blob/5d5e3bf5bc8089eba5146614c062a9b52f21747f/containers/docker/entrypoint.sh#L22) as we are configuring a theme via environment variables causing the assets:precompile to run which fails (for the config, see Deployment manifest below).
I am not entirely sure why this is failing, but the logs suggest it is trying to delete files that are part of the image, which does not work out.

## 🔬 How To Reproduce

Change container image tag to anything higher than 1.49.x with the following k8s Deployment manifest:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: passwordpusher
  namespace: vbc-passwordpusher
spec:
  replicas: 0
  selector:
    matchLabels:
      app: vbc-passwordpusher
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vbc-passwordpusher
    spec:
      volumes:
        - name: cache
          emptyDir:
            sizeLimit: 100Mi
      containers:
        - name: passwordpusher
          image: 'pglombardo/pwpush:1.51'
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-passwordpusher-app
                  key: uri
            - name: PWP__SHOW_GDPR_CONSENT_BANNER
              value: 'false'
            - name: PWP__TIMEZONE
              value: Europe/Vienna
            - name: PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT
              value: '5'
            - name: PWP__PW__EXPIRE_AFTER_DAYS_MAX
              value: '14'
            - name: PWP__PW__EXPIRE_AFTER_VIEWS_DEFAULT
              value: '1'
            - name: PWP__PW__EXPIRE_AFTER_VIEWS_MAX
              value: '14'
            - name: PWP__PW__ENABLE_DELETABLE_PUSHES
              value: 'true'
            - name: PWP__PW__RETRIEVAL_STEP_DEFAULT
              value: 'true'
            - name: PWP__PW__ENABLE_BLUR
              value: 'false'
            - name: PWP__BRAND__TITLE
              value: VBC Secure Secret Sharing
            - name: PWP__BRAND__TAGLINE
              value: powered by Password Pusher
            - name: PWP__BRAND__SHOW_FOOTER_MENU
              value: 'false'
            - name: PWP__BRAND__LIGHT_LOGO
              value: 'https://cdn.vbc.ac.at/public/vbc_logo_transparent.png'
            - name: PWP__BRAND__DARK_LOGO
              value: 'https://cdn.vbc.ac.at/public/vbc_logo_transparent_darkmode.png'
            - name: PWP__THEME
              value: yeti
            - name: PWP__LOG_TO_STDOUT
              value: 'true'
            - name: PWP__GEN__SEPARATORS
              value: '-.!$%'
            - name: PWP__GEN__MAX_SYLLABLE_LENGTH
              value: '3'
            - name: PWP__GEN__MIN_SYLLABLE_LENGTH
              value: '3'
            - name: PWP__GEN__SYLLABLES_COUNT
              value: '4'
            - name: PWP__GEN__CONSONANTS
              value: bcdfghklmnprstv
            - name: PWP__GEN__VOWELS
              value: aeiou
          resources: {}
          volumeMounts:
            - name: cache
              mountPath: /opt/PasswordPusher/tmp/cache
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

### Environment

Where are you running/using Password Pusher?

- [ X] Other (please specify): RedHat OpenShift 4.16

If applicable, what version of Password Pusher?

1.50 or higher

## 📈 Expected behavior

The container should start successfully.

## 📎 Additional context

Log files for latest 1.50 and 1.51 versions attached

[passwordpusher-1.51.13.log](https://github.com/user-attachments/files/19680104/passwordpusher-1.51.13.log)
[passwordpusher-1.50.18.log](https://github.com/user-attachments/files/19680103/passwordpusher-1.50.18.log)

**Comment by mgollo** [comment]
Of course, if you want/need to test something on an OpenShift environment, please let me know!

**Comment by mgollo** [comment]
Hi,
Unfortunately, the security context constraints of OpenShift do not allow to set the uid/gid to such values. For every namespace, the range of allowed uid/gids is predefined, but cannot be predicted as far as I know.
We have had similar issues with images for R shiny applications for which we solved this by adding something like this to the entrypoint:
```
tempfile=$(mktemp)
sed -e "s/^pwpusher.*//g" /etc/passwd > $tempfile
cp $tempfile /etc/passwd
echo "pwpusher:x:$(id -u):$(id -g)::/tmp:/bin/bash" >> /etc/passwd
rm -f $tempfile
```

That way, the pwpusher user (who in the image has uid 1000) gets assigned the uid the container is run with.
I will try to build an image with an adapted entrypoint and let you know if this changes anything.

**Comment by mgollo** [comment]
I have also found this in the OKD docs, suggesting to make everything owned by the root group:
https://docs.okd.io/latest/openshift_images/create-images.html#use-uid_create-images

**Comment by mgollo** [comment]
I have adapted the Dockerfile to use the root group instead of a separate pwpusher group. With this change, the image works on OpenShift. See the commit referenced above. If that solution is acceptable, I can open a PR.

**Comment by pglombardo** [comment]
Cool that this fixes OpenShift but using a root group introduces a security risk for everyone else. :-(

I should potentially make the UID & GID configurable via environment variables...

If you want to build your own containers, you can override the UID & GID values at build time: 

   docker build --build-arg UID=2000 --build-arg GID=2000 -t pwpush-custom .

I'll give this a bit more thought on how to best fix...

**Comment by mgollo** [comment]
I would rather not want to manage a fork just for this. This kind of issue unfortunately applies to quite a lot of images. E.g. for NGINX, the official Docker Hub image does not work on OpenShift and the developers manage an "unpriviliged" version of the image. I don't know how much effort it would be to template the Dockerfile to offer two different versions, but I will try to find out how this is handled for nginx.

**Comment by mgollo** [comment]
Looks like the NGINX developers basically do what I implemented for the unprivileged container (plus change the default ports to >1024), the code starts here: https://github.com/nginx/docker-nginx-unprivileged/blob/69dec3fc07d2e604fa4fde8b18513dd406fc747a/Dockerfile-alpine-slim.template#L110

**Comment by mgollo** [comment]
Unfortunately, my knowledge of GitHub actions is close to zero, but I believe with the (ugly, duplicated) code in the commit above, a second image with GID set to 0 should be built and I think this should work on OpenShift. Can we somehow test this?

**Comment by mgollo** [comment]
No, sorry, this is not enough, as this would lead to a GID conflict, it also needs adaptations of the Dockerfile. I will have a look at this.

**Comment by pglombardo** [comment]
Hi @mgollo - good progress but we might be going down a rabbit hole.  Can you get a shell into the `latest` container and run the following?

In normal Docker, to get a shell: `docker exec -it <containerId> bash`

1. `id`
2. `ls -lh public`
3. `ls -lh app/assets/stylesheets/themes/selected.css`
4. `touch app/assets/stylesheets/themes/test.txt && echo $?`

**Comment by mgollo** [comment]
I can try out the latest tag later today and see if it starts on our staging system.
In the meantime I have pushed a new commit with minor adaptations of the Dockerfile that I could build locally with podman both with the default GID and GID 0.

**Comment by pglombardo** [comment]
You can probably get any tag to run to run the commands above by removing the PWP__THEME and PWP_PRECOMPILE environment variables because that is where the issue is.

**Comment by mgollo** [comment]
Hi,
Without PWP_THEME set, it works indeed. Is there another way to configure the default theme?
With the variable set, the error remains.
If you have a look at the changes to the Dockerfile for creating an unprivileged container, I hope you agree the changes are minimal. With the github actions, I am not sure whether this could be done in a more streamlined way without lots of duplicated code.

**Comment by mgollo** [comment]
Sorry for only getting back with the requested information now. Unfortunately, I was quite busy with other projects.
Here is the output of the commands you requested after removing the PWP_THEME variable from the environment:
```
/opt/PasswordPusher $ id
uid=1000700000(1000700000) gid=0(root) groups=0(root),1000700000
/opt/PasswordPusher $ ls -lh public
total 72K    
-rw-r--r--    1 pwpusher pwpusher     632 Apr 22 09:42 404.html
-rw-r--r--    1 pwpusher pwpusher    1.6K Apr 22 09:42 406-unsupported-browser.html
-rw-r--r--    1 pwpusher pwpusher    1.7K Apr 22 09:42 422.html
-rw-r--r--    1 pwpusher pwpusher    1.9K Apr 22 09:42 500.html
drwxr-xr-x    6 pwpusher pwpusher   12.0K Apr 22 09:47 assets
-rw-r--r--    1 pwpusher pwpusher    1.1K Apr 22 09:42 favicon.ico
drwxr-xr-x    2 pwpusher pwpusher   24.0K Apr 22 09:42 files
lrwxrwxrwx    1 pwpusher pwpusher      32 Apr 22 09:42 flags -> ../node_modules/flag-icons/flags
-rw-r--r--    1 pwpusher pwpusher    1.9K Apr 22 09:42 maintenance.html
-rw-r--r--    1 pwpusher pwpusher     113 Apr 22 09:42 robots.txt
/opt/PasswordPusher $ ls -lh app/assets/stylesheets/themes/selected.css
lrwxrwxrwx    1 pwpusher pwpusher      61 Apr 22 09:46 app/assets/stylesheets/themes/selected.css -> /opt/PasswordPusher/app/assets/stylesheets/themes/default.css
/opt/PasswordPusher $ touch app/assets/stylesheets/themes/test.txt; echo $?
touch: app/assets/stylesheets/themes/test.txt: Permission denied
1
```

**Comment by frenault** [comment]
Hi there! I might be able to help. I’ve deployed **pwpusher** on **OpenShift 4.16**, and folder permissions were tricky due to OpenShift’s `rootless` pod policy.  

### My Setup:
- The app runs with this `securityContext`:
  ```yaml
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  ```
- Required a **ServiceAccount** with the `anyuid` SCC.

### Steps:
1. Switch to your project:
   ```sh
   oc project <your-project>
   ```
2. Create a ServiceAccount:
   ```sh
   oc create sa <your-service-account>
   ```
3. Grant `anyuid` permissions:
   ```sh
   oc adm policy add-scc-to-user anyuid -z <your-service-account>
   ```
4. Assign the ServiceAccount to your Deployment:
   ```sh
   oc set serviceaccount deployment <your-deployment> <your-service-account>
   ```

**Reference**:  
[OpenShift 4.10: Managing Security Context Constraints](https://docs.openshift.com/container-platform/4.10/authentication/managing-security-context-constraints.html#default-sccs_configuring-internal-oauth)

**Comment by mgollo** [comment]
Hi @frenault ,
We are aware of this solution, however, using the anyuid SCC is not an option for us.

**Comment by frenault** [comment]
> Hi [@frenault](https://github.com/frenault) , We are aware of this solution, however, using the anyuid SCC is not an option for us.

Okay. I hope you can find a solution that doesn’t require using SCC. I initially tried to avoid it too, but it ended up being the solution recommended by my cluster administrator.

Just out of curiosity—do we really only need to map the cache directory? In my previous attempts, I mapped the entire /opt/PasswordPusher/ directory using emptyDir, because the pod was failing when trying to create /opt/PasswordPusher/log due to a permission error.

**Comment by ptrovatelli** [comment]
Hello,
I was able to deploy to openshift (ephemeral) by
- using EmptyDir volumes for log and tmp
- relocating the sqllite database to /tmp using `DATABASE_URL` variable override

I don't use a custom theme so it's not answering the selected.css file issue - although a similar solution could maybe be used.

I've tried putting the whole db folder on emptydir but it didn't work (I think it basically erased the other db/* files from the container, while we only want those files to be manipulated apart: `db.sqlite3`, `db.sqlite3-shm`, `db.sqlite3-wal`)

Example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwpush-ephemeral
  name: pwpush-ephemeral
  namespace: xxx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pwpush-ephemeral
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pwpush-ephemeral
    spec:
      containers:
      - image: pglombardo/pwpush:1.62
        imagePullPolicy: Always
        name: pwpush-ephemeral
        env:
        - name: DATABASE_URL
          value: "sqlite3:/tmp/db.sqlite3"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/PasswordPusher/log
          name: log-volume
        - mountPath: /opt/PasswordPusher/tmp
          name: tmp-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: log-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 500Mi
```

**Comment by ptrovatelli** [comment]
or we can even put the database file onto a PVC; seems cleaner than /tmp, and it's not so ephemeral now, the database persists after a pod restart as long as the PVC is not deleted

Add a storageClassName or not in your PVC depending on your cluster configuration
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pwpush-db-claim
spec:
  storageClassName: xxx
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwpush-ephemeral
  name: pwpush-ephemeral
  namespace: xxx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pwpush-ephemeral
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pwpush-ephemeral
    spec:
      containers:
      - image: pglombardo/pwpush:1.62
        imagePullPolicy: Always
        name: pwpush-ephemeral
        env:
        - name: DATABASE_URL
          value: "sqlite3:/opt/PasswordPusher/db-file/db.sqlite3"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/PasswordPusher/log
          name: log-volume
        - mountPath: /opt/PasswordPusher/tmp
          name: tmp-volume
        - mountPath: /opt/PasswordPusher/db-file
          name: pwpush-db-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: log-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: pwpush-db-volume
        persistentVolumeClaim:
          claimName: pwpush-db-claim
```

(need to use deploy strategy `Recreate` unless your PV provider supports `ReadWriteMany`)
