### ISSUE TITLE
Password Show View - End User Instructions

### ISSUE THREAD

**Issue by Viajaz** [pglombardo/PasswordPusher#409]
The Password Show View at https://github.com/pglombardo/PasswordPusher/blob/master/app/views/passwords/show.html.erb gives the user the following instruction:

> Please obtain and securely store this password elsewhere, ideally in a password manager.

This instruction is not always applicable to common scenarios (eg: temporary passwords that are to be changed upon login, temporary passwords or PINs that should not be stored at all) that. This has confused users.

Whilst I understand I can override this text in relevant locale files (Eg: https://github.com/pglombardo/PasswordPusher/blob/master/config/locales/gettext/app.pot ) I think gives that this affects such common uses maybe this instruction text should be reviewed and changed.

**Comment by pglombardo** [comment]
Good suggestion - thanks!  I'll see if I can make that message configurable, changeable etc...

**Comment by Viajaz** [comment]
Could the regional fallbacks feature in [translation.io](https://translation.io/docs/guide-to-translate-your-rails-applications) be used to accommodate for this? @pglombardo 

I am trying to think of a way to override the text in locales that preserves the original gettext .mo/.po files. Whilst I can obviously just override/rebuild them with my own, we run PasswordPusher along with https://github.com/containrrr/watchtower and having to do change management every PasswordPusher update, to ensure .po's haven't changed, is tedious.

**Comment by pglombardo** [comment]
Such a late reply @Viajaz - apologies.  This got lost in the crowd.

I understand what you mean with the .mo/.po files.  IMO the easier solution is to add that string to the [config/settings.yml](https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml) with locales.  For example:

```yaml
text:
  show_instructions:
    en: "Please obtain and securely store this password elsewhere, ideally in a password manager."
    it: "Si prega di ottenere e conservare in modo sicuro questa password altrove, idealmente in un gestore di password."
    # ... etc...
```
It's the only manageable way I see to allow users to add custom strings.

Let me know what you think.  It's not that big of a change - documentation work may be bigger.
