### ISSUE TITLE
default expiration values are ignored

### ISSUE THREAD

**Issue by 4001982248998** [pglombardo/PasswordPusher#465]
Hi,

I am trying to configure a different default expiration values, but they are not honored. I am using a `docker-compose.yml` file like that:

```yaml
version: '2.1'

services:
  postgres:
    image: docker.io/postgres:10
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: …
      POSTGRES_PASSWORD: …
      POSTGRES_DB: …

  passwordpusher:
    image: docker.io/pglombardo/pwpush-postgres:release
    ports:
      - "5100:5100"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      PWP__BRAND__TITLE: … # working
      PWP__BRAND__TAGLINE: … # working
      PWP__BRAND__SHOW_FOOTER_MENU: false  # working
      PWP__EXPIRE_AFTER_DAYS_DEFAULT: 7  # is being ignored
      PWP__EXPIRE_AFTER_DAYS_MAX: 21  # is being ignored
      PWP__EXPIRE_AFTER_VIEWS_DEFAULT: 1  # is being ignored
```

Am I doing anything wrong, or is that a defect?
