### ISSUE TITLE
Branding issues

### ISSUE THREAD

**Issue by xA8EYLgMSN43oEHC** [pglombardo/PasswordPusher#538]
## 🐛 Bug Report

Branding doesn't seem to work completely, or i'm doing something wrong.
- The logo works when signed in or when anonymous is allowed.
- On the sign in page the logo is still the default logo-transparent-sm-dark-bare.
- The favicon is the default 16x16

## 🔬 How To Reproduce

edit  docker-compose.yml as below
docker compose up

### Code sample
Part of the docker-compose.yml
```
  passwordpusher:
    image: docker.io/pglombardo/pwpush-postgres:latest
    volumes:
      - /opt/PasswordPusher/config/settings.yml:/opt/PasswordPusher/config/settings.yml
      - /opt/PasswordPusher/public/custom_images:/opt/PasswordPusher/public/custom_images
      - /opt/PasswordPusher/log:/opt/PasswordPusher/log
    ports:
      - "127.0.0.1:5100:5100"
    depends_on:
      - postgres
    links:
     - postgres:postgres
    environment:
      PWP__BRAND__LIGHT_LOGO: '/custom_images/test_logo_188.png'
      PWP__BRAND__DARK_LOGO: '/custom_images/test_logo_188.png'
      PWP__BRAND__ICON_16x16: '/custom_images/favicon-16x16.png'

```

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [x] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

## 📈 Expected behavior

Expected icons and logos to change
