### ISSUE TITLE
Sending emails using ssl/tls conection fails

### ISSUE THREAD

**Issue by tesudacochino** [pglombardo/PasswordPusher#754]
## 🐛 Bug Report
I try to send any notification by mail using an SSL/TLS connection and I get an error message on the server.

## 🔬 How To Reproduce

To reproduce it, all you have to do is register a new user
These are the logs of my mail server
```
Jan 26 16:25:11 mail postfix/smtps/smtpd[130056]: connect from unknown[192.168.4.120]
Jan 26 16:25:11 mail postfix/smtps/smtpd[130056]: setting up TLS connection from unknown[192.168.4.120]
Jan 26 16:25:11 mail postfix/smtps/smtpd[130056]: unknown[192.168.4.120]: TLS cipher list "aNULL:-aNULL:HIGH:@STRENGTH:!aNULL:!MD5:!DES:!ADH:!RC4:!PSD:!SRP:!3DES:!eNULL"
Jan 26 16:25:21 mail postfix/smtps/smtpd[130056]: SSL_accept error from unknown[192.168.4.120]: lost connection
Jan 26 16:25:21 mail postfix/smtps/smtpd[130056]: lost connection after CONNECT from unknown[192.168.4.120]
Jan 26 16:25:21 mail postfix/smtps/smtpd[130056]: disconnect from unknown[192.168.4.120] ehlo=1 auth=0/1 commands=1/2
```
The error returned by passwordpusher with PWP__MAIL__RAISE_DELIVERY_ERRORS: true
![imagen](https://user-images.githubusercontent.com/13074983/214887429-8a02c644-242d-46f6-a1c0-b87dccfb2756.png)
```
version: '2.1'
services:

  passwordpusher:
    image: pglombardo/pwpush-ephemeral:latest
    container_name: passwordpusher
    hostname: passwordpusher.local
    restart: always
    environment:
      PWP__ENABLE_LOGINS: true
      PWP__ALLOW_ANONYMOUS: true
      PWP__MAIL__SMTP_STARTTLS: false
      PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO: true
      # PWP__MAIL__RAISE_DELIVERY_ERRORS: true
      PWP__HOST_PROTOCOL: http
      PWP__MAIL__SMTP_ADDRESS: 192.168.1.113
      PWP__MAIL__SMTP_PORT: 465
      PWP__MAIL__SMTP_USER_NAME: ${USER_MAIL}
      PWP__MAIL__SMTP_PASSWORD: ${USER_PASSWORD}
      PWP__MAIL__MAILER_SENDER: ${MAILER_SENDER}
      PWP__HOST_DOMAIN: ${HOST_DOMAIN}
    ports:
      - "5100:5100"
```

### Environment

Where are you running/using Password Pusher?

- [x] Docker
  - [X] pwpush-ephemeral

I tried latest and stable docker versión.

## 📈 Expected behavior

Receive an email :-)

## 📎 Additional context

This is my configuration of my Thunderbird mail client.
![imagen](https://user-images.githubusercontent.com/13074983/214886858-6af917e0-d173-443c-bbf7-c2ee45d68bf6.png)

**Comment by pglombardo** [comment]
HI @tesudacochino  - apologies for the issue.  I've oddly had a couple reports of this lately despite no changes in the mail delivery.

To better diagnose, could you open a console in the pwpush container and run the following:

```
docker exec -it <containerId> /bin/bash
./bin/rails console
Rails.application.config.action_mailer.smtp_settings
```

That last command will output the Mail settings.  Could you post that here without any sensitive information?

Then run this code snippet to manually send an email. Replace those email addresses with something valid:

```ruby
Mail.deliver do
  to 'your@email.com'
  from 'your@email.com'
  subject 'testing mail'
  body 'testing mail'
end
```

Could you let me know what the output is. And did you get the email?

**Comment by pglombardo** [comment]
Setting `PWP__MAIL__SMTP_STARTTLS` to `true` may be worth trying too.

**Comment by tesudacochino** [comment]
Hi @pglombardo  

thanks for your quick reply. I have tried the configuration you asked for.

docker-compose.yml file
```
version: '2.1'
services:

  passwordpusher:
    image: pglombardo/pwpush-ephemeral:latest
    container_name: passwordpusher
    hostname: passwordpusher.local
    restart: always
    environment:
      PWP__ENABLE_LOGINS: true
      PWP__ALLOW_ANONYMOUS: true
      PWP__MAIL__SMTP_STARTTLS: true
      PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO: true
      PWP__MAIL__RAISE_DELIVERY_ERRORS: true
      PWP__HOST_PROTOCOL: http
      PWP__MAIL__SMTP_ADDRESS: 192.168.1.113
      PWP__MAIL__SMTP_PORT: 465
      PWP__MAIL__SMTP_USER_NAME: ${USER_MAIL}
      PWP__MAIL__SMTP_PASSWORD: ${USER_PASSWORD}
      PWP__MAIL__MAILER_SENDER: ${MAILER_SENDER}
      PWP__HOST_DOMAIN: ${HOST_DOMAIN}
    ports:
      - "5100:5100"
```
Ruby console:
```
$ /opt/PasswordPusher/bin/rails console 
Loading private environment (Rails 7.0.4.1)
irb(main):001:0> Rails.application.config.action_mailer.smtp_settings
=> 
{:address=>"192.168.1.113",
 :port=>465,
 :user_name=>"xxxx@xxxxx.com",
 :password=>"xxxxx",
 :authentication=>"plain",
 :enable_starttls_auto=>true,
 :open_timeout=>10,
 :read_timeout=>10}
irb(main):002:1* Mail.deliver do
irb(main):003:1*   to 'sxxxx@xxxx.com'
irb(main):004:1*   from 'sxxxx@xxxxx.com'
irb(main):005:1*   subject 'testing mail'
irb(main):006:1*   body 'testing mail'
irb(main):007:0> end
/usr/local/lib/ruby/3.2.0/socket.rb:1217:in `__connect_nonblock': Cannot assign requested address - connect(2) for [::1]:25 (Errno::EADDRNOTAVAIL)
irb(main):008:0>
```
