### ISSUE TITLE
Ability to set colours for additional branding

### ISSUE THREAD

**Issue by JeshuaEdgar** [pglombardo/PasswordPusher#762]
## 🚀 Feature Request

Add the ability to set hex codes for primary/secondary colours for more branding options, either in the environment variables or in the ```settings.yml```

## 🔈 Motivation

PasswordPusher is awesome, it would be even more awesome if we could customise it a little more for branding purposes.

**Comment by rvdwegen** [comment]
I've been playing with the settings a bit.

If you:
- Set the title and tagline to blank
- Add your own logo
- Disable the footer menu

You get to a situation where it's just the save defaults button left that's yellow, the rest of the highlights are blue.

**Comment by pglombardo** [comment]
Let me add a quick but effective hack that will let you apply any theme.

![Screenshot 2023-02-04 at 11 07 40](https://user-images.githubusercontent.com/395132/216761301-403c4d1c-1c5b-475d-acbe-36b63c6606f6.png)

Password Pusher is built with [Bootstrap](https://getbootstrap.com) - a CSS library that supports themes.

So you can download a theme from a site like [Bootswatch](https://bootswatch.com) (download the `bootstrap.css` theme file - not the `min` or `variables` versions) and then overwrite the existing theme in Password Pusher.

A resulting docker command would be:

```sh
docker run -e PWP_PRECOMPILE=true --mount type=bind,source=/path/to/bootstrap.css,target=/opt/PasswordPusher/app/assets/stylesheets/bootstrap-litera.css -p 5100:5100 pglombardo/pwpush-ephemeral:1.25.5
```

or the `docker-compose.yml` equivalent:

```
version: '2.1'
services:

  pwpush:
    image: docker.io/pglombardo/pwpush-ephemeral:1.25.5
    ports:
      - "5100:5100"
    environment:
      PWP_PRECOMPILE: 'true'
    volumes:
      - type: bind
        source: /path/to/bootstrap.css
        target: /opt/PasswordPusher/app/assets/stylesheets/bootstrap-litera.css

```

Here's the Bootswatch "Minty" theme:

![Screenshot 2023-02-04 at 11 32 39](https://user-images.githubusercontent.com/395132/216762196-069fed0f-0a49-42a5-9656-21d9a5e3d92e.png)

I hope this helps.  I intended to ship built in themes and add a theme selector eventually but this should work for now.  Pretty cool no?
