### ISSUE TITLE
Force light theme

### ISSUE THREAD

**Issue by jstilwell** [pglombardo/PasswordPusher#861]
## 🚀 Feature Request

A setting toggle to force either light or dark themes.

## 🔈 Motivation

I understand that the theme is decided via user preference, but I would like to be able to force the light theme in a production environment because it looks more professional.

**Comment by pglombardo** [comment]
Hi @jstilwell - fair request.  You will be able to disable this with the custom CSS option that will be added in https://github.com/pglombardo/PasswordPusher/pull/824

An environment variable toggle would be nice though.  I'll see what we can do.  Thanks for filing!

**Comment by pglombardo** [comment]
Hi @jstilwell,

So now that themes support is out, the best way to enforce just a light theme is to use one of the [custom themes](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#configuring-a-theme).  They don't have a dark mode.

If you want to further customise, you can add [custom CSS](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#how-to-add-custom-css) to make some overrides.

I hope this helps - let me know!

**Comment by L041S** [comment]
Hello, I’m trying to achieve this with custom css. I’m using docker and added the PWP_PRECOMPILE=true and a —env with my custom.css location but the dark theme is still there. I added

:root {
  color-scheme: only light;
}

in this file. Is it the wrong code ?

**Comment by pglombardo** [comment]
Hi @L041S - I tried your CSS as well and couldn't get it to work either.  I also tested directly in the browser console - the CSS doesn't affect the application CSS.

I then tried:

```css
/* Firefox */
@media (prefers-color-scheme: dark) {
    :root {
        color-scheme: light;
    }
}

/* Chrome */
@media (forced-colors: active) {
    :root {
        color-scheme: light;
    }
}
```

also with no affect.  If there was a magic CSS snippet that could disable dark mode, adding it to `custom.css` would be the right move...
