### ISSUE TITLE
Upload large files

### ISSUE THREAD

**Issue by Raifuruu** [pglombardo/PasswordPusher#903]
Hello,

I would like to know if there is a block for uploading large files? Because I try to upload small files and it works, but on larger files (about 3 GB) the loading bar remains blocked and nothing happens

Thank you for this project and this work

**Comment by pglombardo** [comment]
Hi @Raifuruu - are you using pwpush.com or self hosted?  (if so what version)

**Comment by pglombardo** [comment]
For sure the largest uploads I've seen uploads are ~5GB.  I've tried digging on what the limitation might be but nothing is immediately evident.  When you upload larger files is there an error in the javascript console?

**Comment by Raifuruu** [comment]
I don't think it's a problem of rights because otherwise the small files wouldn't work too

**Comment by Raifuruu** [comment]
I will still look at the logs and give you the content

Thanks a lot for your work and your answers

**Comment by pglombardo** [comment]
> I don't think it's a problem of rights because otherwise the small files wouldn't work too

I couldn't get any file to upload large or small.  I tried both Vivaldi/chrome and Safari.  Safari did reveal a bit more info though:

![Screenshot 2023-03-17 at 10 09 03](https://user-images.githubusercontent.com/395132/225861434-3624c84a-c155-46f2-be25-efaae7c72ade.png)

IIRC this was a bug in an early version.  If this is the case, then updating to to the `release` tag should fix this.

**Comment by Raifuruu** [comment]
However, for me and for all users who use the tool, sending small files works well : https://kspass.keycloud.fr/fr/f/vx1igzk935boypvqaq/r

I'm going to look at the version right now, and I'll let you know

**Comment by Raifuruu** [comment]
Here are the contents of my docker-compose.yml :

```
version: '3.3'
secrets:
  password_compte_commercial:
    external: true

services:
  postgres:
    image: docker.io/postgres:10
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: passwordpusher_user
      POSTGRES_PASSWORD: passwordpusher_passwd
      POSTGRES_DB: passwordpusher_db

  passwordpusher:
    image: docker.io/pglombardo/pwpush-postgres:release
    secrets:
      - password_compte_commercial
    volumes:
      - /lib/KSPASS/Files:/opt/PasswordPusher/storage:rw
      - type: bind
        source: /lib/KSPASS/Files/bootstrap.css
        target: /opt/PasswordPusher/app/assets/stylesheets/bootstrap-litera.css
    ports:
      - "5100:5100"
    depends_on:
      - postgres
    links:
     - postgres:postgres
    environment:
     PUID: "1000"
     PGID: "1000"
     PWP_PRECOMPILE: 'true'
     PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT: "1"
     PWP__PW__EXPIRE_AFTER_DAYS_MIN: "1"
     PWP__PW__EXPIRE_AFTER_DAYS_MAX: "5"
     PWP__PW__EXPIRE_AFTER_VIEWS_DEFAULT: "1"
     PWP__PW__EXPIRE_AFTER_VIEWS_MIN: "1"
     PWP__PW__EXPIRE_AFTER_VIEWS_MAX: "5"
     PWP__PW__RETRIEVAL_STEP_DEFAULT: "true"
     PWP__BRAND__TITLE: ""
     PWP__BRAND__TAGLINE: ""
     PWP__BRAND__LIGHT_LOGO: "https://www.keysource.eu/image/catalog/logo-kspass.png"
     PWP__BRAND__DARK_LOGO: "https://www.keysource.eu/image/catalog/logo-kspass.png"
     PWP__ENABLE_LOGINS: "true"
     PWP__HOST_PROTOCOL: 'https'
     PWP__HOST_DOMAIN: 'kspass.keycloud.fr'
     PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO: 'false'
     PWP__MAIL__SMTP_PORT: '587'
     PWP__MAIL__SMTP_ADDRESS: "smtp.orange.fr"
     PWP__MAIL__MAILER_SENDER: XXX
     PWP__MAIL__SMTP_USER_NAME: XXX
     PWP__MAIL__SMTP_PASSWORD: XXX
     PWP__MAIL__SMTP_AUTHENTICATION: 'plain'
     PWP__MAIL__RAISE_DELIVERY_ERRORS: 'true'
     PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO: 'false'
     PWP__ENABLE_FILE_PUSHES: "true"
     PWP__FILES__STORAGE: "local"
     PWP__FILES__EXPIRE_AFTER_DAYS_MAX: "7"
     PWP__FILES__EXPIRE_AFTER_VIEWS_MAX: "3"
     PWP__FILES__RETRIEVAL_STEP_DEFAULT: "true"
     PWP__DEFAULT_LOCALE: "fr"
     PWP__BRAND__ICON_32x32: "https://www.keysource.eu/image/catalog/favicon-kspass.png"
     PWP__BRAND__ICON_96x96: "https://www.keysource.eu/image/catalog/favicon-kspass.png"
     PWP__BRAND__ICON_16x16: "https://www.keysource.eu/image/catalog/favicon-kspass.png"
     PWP__BRAND__ICON_144x144: "https://www.keysource.eu/image/catalog/favicon-kspass.png"
     PWP__BRAND__ICON_57x57: "https://www.keysource.eu/image/catalog/favicon-kspass.png"

```
