### ISSUE TITLE
Mixed content behind reverse proxy

### ISSUE THREAD

**Issue by D1s0rdu8** [pglombardo/PasswordPusher#904]
Docker MySQL version.

```
 pwpush:
    <<: *common-keys-apps
    image: pglombardo/pwpush-mysql:1.23.10
    container_name: pwpush
    networks:
      t2_proxy:
        ipv4_address: ***.***.***.***
    environment:
      <<: *default-tz-puid-pgid
      DATABASE_URL: "mysql2://passwordpusher_user:**********@mariadb:3306/pwdpushdb"
      DELETABLE_PASSWORDS_ENABLED: "true"
      PWP__BRAND__SHOW_FOOTER_MENU: "false"
      PWP__BRAND__TITLE: "Secrets sharing"
      PWP__BRAND__TAGLINE: "NEVER email passwords again"
      PWP__OVERRIDE_BASE_URL: "https://secret.domain.com"
      PWP__BRAND__LIGHT_LOGO: "/packs/media/img/custom/blue.png"
      PWP__BRAND__DARK_LOGO: "/packs/media/img/custom/white.png"
      PWP__THROTTLING__DAILY: "10000"
      PWP__THROTTLING__HOURLY: "1000"
      PWP__THROTTLING__MINUTE: "300"
      PWP__THROTTLING__SECOND: "20"
      PWPUSH_MASTER_KEY: "*******"
    volumes:
      - /docker/appdata/pwdpush:/opt/PasswordPusher/public/packs/media/img/custom
    ports:
      - 8097:5100
```

When trying to update to v1.26.6 I have mixed content error behind a reverse proxy when using the push button.
On my current version 1.23.10 it's working without any issue.

```
Mixed Content: The page at 'https://secret.domain.com/' was loaded over HTTPS, but requested an insecure resource 'http://secret.domain.com/en/p/7d75lmjr694ybna/preview'. This request has been blocked; the content must be served over HTTPS.
```

Any idea what I could try to be able to update to the last release ?

**Comment by D1s0rdu8** [comment]
I updated to 1.24.0 with no issue, It is broken from the version 1.24.1

**Comment by pglombardo** [comment]
@D1s0rdu8 is right although I'm not sure from which version yet.  

Something in 1.26.x has broke for sure with odd symptoms.  As usual the `release` tag is stable (and is also why I haven't updated that tag recently).

I'll dig into this soon - thanks for pointing this out!

**Comment by D1s0rdu8** [comment]
It breaks between 1.24.0 and 1.24.1 with this change : #674

**Comment by pglombardo** [comment]
Hi @D1s0rdu8 a couple of ideas that may likely resolve this:

* Make sure your reverse proxy properly forwards the X-Forwarded-Host, X-Forwarded-Port and X-Forwarded-Proto headers.  More info [here](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#proxies).

* You could try setting `FORCE_SSL`.  Although that setting is old, it may have an effect if the above didn't resolve the issue.  The documentation for that is [here](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#forcing-ssl-links).

Let me know what you find.

**Comment by fromage9747** [comment]
@pglombardo I have just started experiencing this issue as well.  When I first set up this docker container, everything was peachy.  There have been no changes made to it since the day I deployed it. 

If I use "FORCE_SSL: true" then I get too many redirects.  X-Forwarded-Host, X-Forwarded-Port and X-Forwarded-Proto have all been set correctly and have been there since day one.

**Comment by pglombardo** [comment]
Hi @fromage9747 which docker tag are you using?  I'm on the road 
but will take a look once I'm back

**Comment by fromage9747** [comment]
@pglombardo docker.io/pglombardo/pwpush-postgres:release

All good.  Drive safe!

**Comment by pglombardo** [comment]
After a couple of attempts, I haven't been able to reproduce this.   I suspect that this is likely related to the Javascript framework in use in combo with the `X-Forwarded` headers.  If so, we may be able to force `http` in another way.

To test this would one of you be willing to follow these steps and let me know if it fixes the mixed content?

Create a file `force-https-fix.rb` with the contents:

```ruby
Rails.application.routes.default_url_options[:protocol] = 'https'
```

Then mount that file into the container into `/opt/PasswordPusher/config/initializers/force-https-fix.rb` using the following command line:

```sh
docker run 
--mount type=bind,source=/path/to/force-https-fix.rb,target=/opt/PasswordPusher/config/initializers/force-https-fix.rb
-p "5100:5100" pglombardo/pwpush-ephemeral:release
``` 

or however you run the specific docker run command.  

Alternatively for Docker compose:

```yaml
volumes:
  - type: bind
    source:/path/to/force-https-fix.rb
    target: /opt/PasswordPusher/config/initializers/force-https-fix.rb
```

It's a slight hail mary but it might be the fix for this issue.

Let me know if either of you could try this out.
